### ISSUE TITLE
Microsoft.Playwright.CLI does not install due to a missing reference to Microsoft.Bcl.AsyncInterfaces

### ISSUE THREAD

**Issue by DanielBailey1001001** [microsoft/playwright-dotnet#1598]
In my Azure DevOps Pipelines yaml I have added the step to install your CLI, but I get an error back. I get the same error locally and saw somebody else had the error in an issue 2 weeks ago and another in a closed issue 2 days ago. What are the steps we are all missing before running "playwright install"?

Here is the .yml:
```
steps:
- powershell: |
   dotnet tool install --global Microsoft.Playwright.CLI
   playwright install
```

Here is the error:
```
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\0b3fa5ca-f94a-4b68-91c2-ba2d45fc51ca.ps1'"
You can invoke the tool using the following command: playwright
Tool 'microsoft.playwright.cli' (version '1.0.0') was successfully installed.
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'Microsoft.Bcl.AsyncInterfaces, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Microsoft.Playwright.CLI.Program.Main(String[] args) in /_/src/Playwright.CLI/Program.cs:line 53
##[error]PowerShell exited with code '1'.
```

**Comment by pavelfeldman** [comment]
As a workaround, you can run `playwright.ps1 install` that is in your output folder.

**Comment by DanielBailey1001001** [comment]
I could not get that workaround to run either. But in case it helps, I have another workaround that worked for me, see this issue: https://github.com/microsoft/playwright-dotnet/issues/1531#issuecomment-868997226
I think the nuget is not putting the .playwright folder into the output directory and that is causing all these issues.

**Comment by DanielBailey1001001** [comment]
Until this gets fixed, this is the yaml I used in Azure DevOps to get Playwright to run my tests in a pipeline, hope it helps someone. Not sure why I need to copy the files twice but that makes it work so I won't argue with it :)

```
- task: CopyFiles@1
  displayName: 'Copy Playwright to bin folder so the running tests can find the browsers'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\packages\Microsoft.Playwright.1.13.0-next-1\.playwright\'
    Contents: '**'
    targetFolder: $(Build.SourcesDirectory)\MyProject\bin\$(buildPlatform)\$(buildConfiguration)\.playwright\

- task: CopyFiles@1
  displayName: 'Copy Playwright to source folder too so the tests can find the library they need'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\packages\Microsoft.Playwright.1.13.0-next-1\.playwright\'
    Contents: '**'
    targetFolder: $(Build.SourcesDirectory)\MyProject\.playwright\

- powershell: |
   $(Build.SourcesDirectory)\packages\Microsoft.Playwright.1.13.0-next-1\.playwright\node\win32_x64\playwright.cmd install
  displayName: 'Install Playwright Browsers'

#Run the web tests
- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    runInParallel: true

```

**Comment by avodovnik** [comment]
I wonder if there's a problem with running `powershell` in your yaml file.

Here's what I did in my example:

```yml
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install -g Microsoft.Playwright.CLI'

- task: CmdLine@2
  inputs:
    script: 'playwright install'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
```
