### ISSUE TITLE
[BUG] Playwright.CreateAsync() is hanging when it's executed by GitHub runner

### ISSUE THREAD

**Issue by op-13** [microsoft/playwright-dotnet#2517]
**Context:**
- Playwright Version: 1.31.1
- Operating System: Windows
- .NET version: .NET Framework 4.7.2
- Browser: Not applicable because it's hanging before any browser interaction
- Extra: 

Please find repro: [https://github.com/op-13/pwtest](https://github.com/op-13/pwtest)

**Code Snippet**

The simple test solution is using VSTest and a simple GitHub actions workflow. The single file has only a dummy test:

```cs
    [TestClass]
    public class SimpleTestWithPlaywright
    {
        [TestMethod]
        public async Task TestMethod1()
        {
            using (var instance = await Playwright.CreateAsync())  // it is hanging in the CreateAsync() call
            {
                Assert.AreEqual(1, 1); // we will never reach this point when the GitHub runner executes this
            }
        }
    }
```

The relevant part of the yaml workflow:

```yml
    - name: Run tests
      shell: powershell
      run: |
        . "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" (Get-ChildItem $currentDirectory -include *.dll -recurse | where {$_.name -match "SimpleTest.dll" -and $_.Directory -notMatch '.*\\obj\\.*'}).FullName
```

**Describe the bug**

The bug is that the code is hanging when it's being executed by the GitHub runner: [link to a sample workflow run](https://github.com/op-13/pwtest/actions/runs/4487804137/jobs/7891632342)
I have to cancel this manually otherwise it would run for hours (until it times out).

If I run the same command from the machine of the runner, it works fine:

![image](https://user-images.githubusercontent.com/128555701/226870378-b65e22e3-a5ec-4a0e-8ffb-3fde9d69df8c.png)

It doesn't make any difference if I run the GitHub runner in an Administrator command prompt or not.
Tested on 5 different machines, including installations of Windows Server 2019 Standard and a Windows 10 Pro.

Also we tried to use Microsoft's [VSTest-action](https://github.com/microsoft/vstest-action), it was still hanging.
