### ISSUE TITLE
Deploy Playwright Deps with install

### ISSUE THREAD

**Issue by aherrick** [microsoft/playwright-dotnet#2643]
### Your question

I'm running Playwright in an Azure Function and it's working great, I just don't want to have it manually download Deps every time it has to spin the Function back up. Is there a way to essentially deploy the Deps with the Function itself so it can just read them locally as part of the deployment? 

Currently I'm running this at the beginning of the Function in order to download what is needed:

`            Microsoft.Playwright.Program.Main(new[] { "install-deps" });
`

**Comment by mxschmitt** [comment]
We recommend our Docker image for that as a base image. This contains all the necessary dependencies which are required to run all Playwright browsers: https://playwright.dev/dotnet/docs/docker

You can also create your own base Docker image in order to have a smaller image if you only want e.g. Chromium, see here: https://playwright.dev/dotnet/docs/browsers#install-browsers

**Comment by aherrick** [comment]
hi @mxschmitt thanks for the response. So there isn't any other way to do this without using Docker?

**Comment by mxschmitt** [comment]
I'm not familiar with Azure Functions, but I don't think so. Usually a pre generated environment like Docker containers is great for that.

**Comment by aherrick** [comment]
BTW I figured this out without using Docker. 

https://github.com/MrSimonC/Playwright-In-Azure-Function-Template

Here is my full GH Action based on the guide template:

```
name: Build and deploy .NET Core application to Function App TappedInFnTweetVenueMenu
on:
  push:
    branches:
    - master
env:
  AZURE_FUNCTIONAPP_NAME: TappedInFnTweetVenueMenu
  AZURE_FUNCTIONAPP_PACKAGE_PATH: ./published
  PLAYWRIGHT_BROWSERS_PATH: ./published/.playwright/ms-playwright
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: .
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"

    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore

    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
      
    - name: Playwright install
      shell: bash
      run: |
        dotnet tool install --global Microsoft.Playwright.CLI
        playwright install chromium
        tar -cvf publish_directory.tar "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"

    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: functionapp
        path: publish_directory.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: functionapp
        path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: functionapp
    - name: Restore artifact with permissions
      shell: bash
      run: |
        mkdir --parents ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        tar xvf publish_directory.tar
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

        # added for playwright
    - name: App Settings Update
      uses: azure/appservice-settings@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        mask-inputs: false
        app-settings-json: '[{ "name": "WEBSITE_MOUNT_ENABLED", "value": 1, "slotSetting": false }, { "name": "FUNCTIONS_WORKER_RUNTIME", "value": "dotnet-isolated", "slotSetting": false }, { "name": "PLAYWRIGHT_BROWSERS_PATH", "value": "/home/site/wwwroot/.playwright/ms-playwright", "slotSetting": false }]'
    - uses: geekyeggo/delete-artifact@v2
      with:
          name: functionapp
```
