### ISSUE TITLE
[Docs]: Provide guidance on running tests using pipeline artifacts

### ISSUE THREAD

**Issue by ianoflynnautomation** [microsoft/playwright-dotnet#3083]
### Page(s)

https://playwright.dev/dotnet/docs/ci

### Description

In our CI pipeline we publish test projects as pipeline artifacts and then download the pipeline artifacts in a later job to run the tests. However, I cannot get this working for playwright, and it does not seem to natively support it.

 I have tried many ways to get this working with no luck and I assume there is no native way to do this. Would be nice if the documentation had a section on this as I assume its a common scenario for a lot of teams

Where in the below do I run 'pwsh playwright.ps1 install/playwright.ps1 install  install-deps' to get this working?

Example build test project job in GitHub actions
```
   - name: 'Set Dotnet Version ${{ inputs.dotnet-version }}'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Install Dependencies
      shell: bash
      run: dotnet restore Everything.sln

    - name: Build Solution
      shell: bash
      run: |
        dotnet build Everything.sln --configuration Release --no-restore

    - name: Publish Test project
      shell: bash
      run:  |
        dotnet publish --property:PublishDir="${{ github.workspace }}/output" tests/${{ inputs.project-pattern }}

    - name: Publish ${{ inputs.artifact-name }} artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ github.workspace }}/output

```

Example run tests 

```
    - name: Download ${{ inputs.test-artifact-name }} Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.test-artifact-name }}
        path: artifacts
        pattern: ${{ inputs.test-project-pattern }} 

    - name: 'Set Dotnet Version ${{ inputs.dotnet-version }}'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }} 

   - name: Run tests
      shell: bash
      working-directory: artifacts
      run: dotnet test *Tests.dll 

```
